language: node_js
node_js:
  - node
before_install:
  - git remote add github "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
script:
  - npm run build
  - git add .
  - "! git diff --staged --quiet"
before_deploy:
  - npm version --force 0.0.$(date +%Y%m%d%H%M%S)
  - git push --follow-tags github HEAD:${TRAVIS_BRANCH}
deploy:
  provider: npm
  email: Gerhut@GMail.com
  api_key: $NPM_TOKEN